/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComputerRouteImport } from './routes/computer'
import { Route as HowToPlayRouteImport } from './routes/how-to-play'
import { Route as PlayRouteImport } from './routes/play'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as GameCodeRouteImport } from './routes/game.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputerRoute = ComputerRouteImport.update({
  id: '/computer',
  path: '/computer',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToPlayRoute = HowToPlayRouteImport.update({
  id: '/how-to-play',
  path: '/how-to-play',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const GameCodeRoute = GameCodeRouteImport.update({
  id: '/game/$code',
  path: '/game/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/computer': typeof ComputerRoute
  '/how-to-play': typeof HowToPlayRoute
  '/play': typeof PlayRoute
  '/rules': typeof RulesRoute
  '/watch': typeof WatchRoute
  '/game/$code': typeof GameCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/computer': typeof ComputerRoute
  '/how-to-play': typeof HowToPlayRoute
  '/play': typeof PlayRoute
  '/rules': typeof RulesRoute
  '/watch': typeof WatchRoute
  '/game/$code': typeof GameCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/computer': typeof ComputerRoute
  '/how-to-play': typeof HowToPlayRoute
  '/play': typeof PlayRoute
  '/rules': typeof RulesRoute
  '/watch': typeof WatchRoute
  '/game/$code': typeof GameCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/computer'
    | '/how-to-play'
    | '/play'
    | '/rules'
    | '/watch'
    | '/game/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/computer'
    | '/how-to-play'
    | '/play'
    | '/rules'
    | '/watch'
    | '/game/$code'
  id:
    | '__root__'
    | '/'
    | '/computer'
    | '/how-to-play'
    | '/play'
    | '/rules'
    | '/watch'
    | '/game/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComputerRoute: typeof ComputerRoute
  HowToPlayRoute: typeof HowToPlayRoute
  PlayRoute: typeof PlayRoute
  RulesRoute: typeof RulesRoute
  WatchRoute: typeof WatchRoute
  GameCodeRoute: typeof GameCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/computer': {
      id: '/computer'
      path: '/computer'
      fullPath: '/computer'
      preLoaderRoute: typeof ComputerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-play': {
      id: '/how-to-play'
      path: '/how-to-play'
      fullPath: '/how-to-play'
      preLoaderRoute: typeof HowToPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$code': {
      id: '/game/$code'
      path: '/game/$code'
      fullPath: '/game/$code'
      preLoaderRoute: typeof GameCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComputerRoute: ComputerRoute,
  HowToPlayRoute: HowToPlayRoute,
  PlayRoute: PlayRoute,
  RulesRoute: RulesRoute,
  WatchRoute: WatchRoute,
  GameCodeRoute: GameCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
